"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomFormFieldType = void 0;
var CustomFormFieldType;
(function (CustomFormFieldType) {
    CustomFormFieldType[CustomFormFieldType["LookupSingle"] = 1] = "LookupSingle";
    CustomFormFieldType[CustomFormFieldType["SystemSingleSegment"] = 2] = "SystemSingleSegment";
    CustomFormFieldType[CustomFormFieldType["SystemMultipleSegment"] = 3] = "SystemMultipleSegment";
    CustomFormFieldType[CustomFormFieldType["SystemSingleCountry"] = 4] = "SystemSingleCountry";
    CustomFormFieldType[CustomFormFieldType["SystemMultipleCountry"] = 5] = "SystemMultipleCountry";
    CustomFormFieldType[CustomFormFieldType["TextSingleLine"] = 6] = "TextSingleLine";
    CustomFormFieldType[CustomFormFieldType["TextMultiLine"] = 7] = "TextMultiLine";
    CustomFormFieldType[CustomFormFieldType["Number"] = 8] = "Number";
    CustomFormFieldType[CustomFormFieldType["Date"] = 9] = "Date";
    CustomFormFieldType[CustomFormFieldType["Boolean"] = 10] = "Boolean";
    CustomFormFieldType[CustomFormFieldType["User"] = 11] = "User";
    CustomFormFieldType[CustomFormFieldType["SystemName"] = 12] = "SystemName";
    CustomFormFieldType[CustomFormFieldType["ActivityReference"] = 13] = "ActivityReference";
    CustomFormFieldType[CustomFormFieldType["InheritedField"] = 14] = "InheritedField";
    CustomFormFieldType[CustomFormFieldType["LookupMultiple"] = 15] = "LookupMultiple";
    CustomFormFieldType[CustomFormFieldType["MultipleUser"] = 16] = "MultipleUser";
    CustomFormFieldType[CustomFormFieldType["DynamicMediator"] = 17] = "DynamicMediator";
    CustomFormFieldType[CustomFormFieldType["DateTime"] = 18] = "DateTime";
    CustomFormFieldType[CustomFormFieldType["Header"] = 19] = "Header";
    CustomFormFieldType[CustomFormFieldType["CalculatedField"] = 20] = "CalculatedField";
})(CustomFormFieldType = exports.CustomFormFieldType || (exports.CustomFormFieldType = {}));
